/**
 * Defines all of the available game rules.
 */
export type GameRuleName =
  | 'announceAdvancements'
  | 'commandBlockOutput'
  | 'disableElytraMovementCheck'
  | 'disableRaids'
  | 'doDaylightCycle'
  | 'doEntityDrops'
  | 'doFireTick'
  | 'doInsomnia'
  | 'doImmediateRespawn'
  | 'doLimitedCrafting'
  | 'doMobLoot'
  | 'doMobSpawning'
  | 'doPatrolSpawning'
  | 'doTileDrops'
  | 'doTraderSpawning'
  | 'doWeatherCycle'
  | 'doWardenSpawning'
  | 'drowningDamage'
  | 'fallDamage'
  | 'fireDamage'
  | 'forgiveDeadPlayers'
  | 'freezeDamage'
  | 'keepInventory'
  | 'logAdminCommands'
  | 'maxCommandChainLength'
  | 'maxEntityCramming'
  | 'mobGriefing'
  | 'naturalRegeneration'
  | 'playersSleepingPercentage'
  | 'randomTickSpeed'
  | 'reducedDebugInfo'
  | 'sendCommandFeedback'
  | 'showDeathMessages'
  | 'spawnRadius'
  | 'spectatorsGenerateChunks'
  | 'universalAnger'
